Fixed typos and added small translations
1950Labs/vuejs.org pull request #104
Opened 2020-01-08 02:58 UTC by Yilber

2020-01-21 01:13 UTC, Yilber commented
@alphacentauri82 here it is.

2020-02-02 18:05 UTC, sxcamacho requested changes

2020-02-02 18:05 UTC, sxcamacho commented on src/v2/guide/class-and-style.md
> +## Enlace de Estilos línea
We should add `en`.

```suggestion
## Enlace de estilos en línea
```

2020-02-02 18:05 UTC, sxcamacho commented on src/v2/guide/class-and-style.md
> +### Sintaxis de Matriz
We were discussing with the rest of the team about what we should use: `Array`, `Arreglo` or  `Matriz` and we decided to keep the `Array` word in English because it is the most common way we use it. So please, don't change `Array` by `Matriz`. On the other hand, If you see the word `Arreglo` in other files, please feel free to change it by `Array`. The rest of the changes look good! Thanks!

2020-02-03 03:25 UTC, Yilber commented on src/v2/guide/class-and-style.md
> +### Sintaxis de Matriz
quick question, is the Spanish section on the readme file up to date?

On the English version of the website, there are names that have changed or have been removed. I would like to keep it all versions updated but I don't know who is still on contributing or who has changed its username.

2020-02-04 16:54 UTC, sxcamacho commented on src/v2/guide/class-and-style.md
> +### Sintaxis de Matriz
Yes, you're right. The correct content is that which contains the original repository. Our repository is outdated.

2020-02-05 01:29 UTC, sxcamacho approved these changes

2020-02-05 01:30 UTC, merged