importante aporte sobre el v-for y el v-if
1950Labs/vuejs.org pull request #105
Opened 2020-02-01 16:23 UTC by carlos00027

en la documentación oficial se encuentra esta importante recomendación

2020-02-02 16:17 UTC, sxcamacho requested changes

2020-02-02 16:17 UTC, sxcamacho commented on src/v2/guide/list.md
> +
Remember to keep a single blank line between the texts, adding the class `tip` should be displayed correctly.

2020-02-02 16:17 UTC, sxcamacho commented on src/v2/guide/list.md
> +nota: Tenga en cuenta que no se recomienda usar v-if y v-for juntos. Consulte la [guía de estilo](https://vuejs.org/v2/style-guide/#Avoid-v-if-with-v-for-essential) para más detalles.
Hey @carlos00027, thanks for noticing this new content! Please, can you update this PR to include the HTML and markup?

```suggestion
<p class="tip">Tenga en cuenta que **no se recomienda** usar `v-if` y `v-for` juntos. Consulte la [guía de estilo](/v2/style-guide/#Avoid-v-if-with-v-for-essential) para más detalles.</p>
```

2020-04-10 17:17 UTC, Tintef commented
@sxcamacho Maybe one of us should make this changes, what do you think? (It's been like 2 months since this PR was opened)

2020-04-10 23:32 UTC, sxcamacho commented
Hey @Tintef, yes... would be great If @carlos00027 could complete it, but If he can't we can tackle it.

2020-04-13 13:53 UTC, sxcamacho approved these changes

2020-04-13 13:53 UTC, merged