Spell check and finish translation of style guide - priority A
1950Labs/vuejs.org pull request #35
Opened 2019-06-08 21:50 UTC by Tintef

2019-06-14 02:19 UTC, FLarra requested changes

2019-06-14 02:19 UTC, FLarra commented on src/v2/style-guide/index.md
> +Se ha descubierto que estas reglas mejoran la legibilidad y / o la experiencia del desarrollador en la mayoría de los proyectos. Su código aún se ejecutará si no las respeta, pero estas excepciones d
I think the `y/o` must be together. Dismiss if I'm wrong.

```suggestion
Se ha descubierto que estas reglas mejoran la legibilidad y/o la experiencia del desarrollador en la mayoría de los proyectos. Su código aún se ejecutará si no las respeta, pero estas excepciones deben ser raras y estar bien justificadas.
```

2019-06-14 02:19 UTC, FLarra commented on src/v2/style-guide/index.md
> +Más allá del atributo `scoped`, El uso de nombres de clase únicos puede ayudar a garantizar que el CSS de terceros no se aplique a su propio HTML. Por ejemplo, muchos proyectos usan los nombres de la
```suggestion
Más allá del atributo `scoped`, el uso de nombres de clase únicos puede ayudar a garantizar que el CSS de terceros no se aplique a su propio HTML. Por ejemplo, muchos proyectos usan los nombres de las clases `button`, ` btn` o `icon`, por lo que incluso si no usan una estrategia como BEM, agregan un prefijo específico de la aplicación y/o componente específico (por ejemplo, `ButtonClose-icon`) puede proporcionar cierta protección.
```

2019-06-14 02:19 UTC, FLarra commented on src/v2/style-guide/index.md
> +Vue utiliza el prefijo `_` para definir sus propias propiedades privadas, entonces, utilizar el mismo prfijo (ej. `_update`) puede causar que una propiedad privada sea sobreescrita. Incluso si usted
```suggestion
Vue utiliza el prefijo `_` para definir sus propias propiedades privadas, entonces, utilizar el mismo prefijo (ej. `_update`) puede causar que una propiedad privada sea sobreescrita. Incluso si usted verifica y Vue no está haciendo uso de dicho nombre, no hay garantía de que este conflicto no surja en una versión futura.
```

2019-06-14 03:02 UTC, FLarra approved these changes

2019-06-17 06:50 UTC, sxcamacho approved these changes

2019-06-17 06:50 UTC, merged