Translate style guide - priority B
1950Labs/vuejs.org pull request #46
Opened 2019-07-04 02:58 UTC by Tintef

2019-07-15 05:16 UTC, sxcamacho commented on src/v2/style-guide/index.md
> +Esto lo ayudará a usted a encontrar de una manera más rápida una componente cuando precise editarlo o verificar como se utiliza.
Typo `una componente` change to `un componente`

2019-07-15 05:21 UTC, sxcamacho commented on src/v2/style-guide/index.md
> +**Los nombres de los archivos de las [componentes single-file](../guide/single-file-components.html) deben ser siempre PascalCase o siempre kebab-case.**
Typo `de las componentes` change to `de los`

2019-07-15 05:22 UTC, sxcamacho commented on src/v2/style-guide/index.md
> +**Las componentes base (también conocidas como componentes de presentación, "tontos", o puros) que aplican estilos y convenciones específicas de la aplicación, deben comenzar con un prefijo específic
Typo `las componentes`

2019-07-15 06:05 UTC, sxcamacho commented on src/v2/style-guide/index.md
> +Estas componentes son la base para la definición de estilos y comportamientos consistentes en la aplicación. Estas **solamente** deben contener:
`Estas componentes` change to `Estos componentes`

2019-07-15 06:09 UTC, sxcamacho commented on src/v2/style-guide/index.md
> +- otras componentes base, y
Typo `otras componentes` change to `otros componentes`

2019-07-15 06:18 UTC, sxcamacho commented on src/v2/style-guide/index.md
> +Sus nombres generalmente incluyen el nombre del elemento que envuelven(por ejemplo `BaseButton`, `BaseTable`), a menos que no exista un elemento para su propósito específico (por ejemplo `BaseIcon`).
- Please, add a space at `envuelven (por ejemplo`
- Plase, change `ellas casi siempre consumirán estas componentes` to `casi siempre consumirán estos componentes` or something like that.

2019-08-05 22:02 UTC, FLarra requested changes

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +El autocompletado de los editores de código funciona mejor cuando se utiliza PascalCase, ya que esta es consistente con la forma en que referenciamos componenten en JS(X) y _templates_, dónde sea pos
Minor suggestion ?)
```suggestion
El autocompletado de los editores de código funciona mejor cuando se utiliza PascalCase, ya que esta es consistente con la forma en que referenciamos componenten en JS(X) y plantillas, dónde sea posible. Sin embargo, nombres de archivos mixtos pueden crear problemas en sistemas de archivos insensibles a las mayúsculas y minúsculas, es por esto que utilizar kebab-case es perfectamente aceptable.
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +- Cuando están organizados alfabéticamente en los editores, los componentes base serán listados todos juntos, volviendose más fácil de identificar.
Small misspelling  here.

```suggestion
- Cuando están organizados alfabéticamente en los editores, los componentes base serán listados todos juntos, volviéndose más fácil de identificar.
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +### Nombres de componentes de instancia úncia <sup data-p="b">altamente recomendado</sup>
Typo here: 

```suggestion
### Nombres de componentes de instancia única <sup data-p="b">altamente recomendado</sup>
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +Esto no quiere decir que la componente solamente es utiliza en una única página, sino que solamente será utilizada una vez _por página_. Este tipo de componente nunca aceptan _props_, dado que son es
A couple of mistakes:

```suggestion
Esto no quiere decir que el componente solamente se utiliza en una única página, sino que solamente será utilizado una vez _por página_. Este tipo de componente nunca aceptan propiedades, dado que son específicas para la aplicación, no del contexto de la misma. Si usted encuentra la necesidad de añadir propiedades, puede ser un buen indicio de que se trata de un componente reusable que solamente se utiliza una vez por página, _por ahora_.
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +- Muchas archivos con nombres similares, haciendo difícil cambiar entre archivos en un editor de código.
```suggestion
- Muchos archivos con nombres similares, haciendo difícil cambiar entre archivos en un editor de código.
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +- Muchas subdirectorios anidados, lo cual incremente el tiempo que toma buscar un componente específico en un editor.
```suggestion
- Muchos subdirectorios anidados, lo cual incrementa el tiempo que toma buscar un componente específico en un editor.
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +En el inglés natural, adjetivos y otros descriptores aparecen tipicamente antes de los sustantivos, mientras que excepciones requiren conectores. Por ejemplo:
Maybe :?
```suggestion
En inglés, adjetivos y otros descriptores aparecen típicamente antes de los sustantivos, mientras que excepciones requieren conectores. Por ejemplo:
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +También observe que **lo qué es considerado "de más alto nivle" será contextual a su aplicación**. Por ejemplo, imagine una aplicación con un formulario de búsqueda. Este puede incluir componentes co
Typo: 

```suggestion
También observe que **lo que es considerado "de más alto nivel" será contextual a su aplicación**. Por ejemplo, imagine una aplicación con un formulario de búsqueda. Este puede incluir componentes como:
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +Los componentes que se cierran automáticamente no solo comunican que no tienen contenido, sino que garantizan que no deben tener contendio. Es la diferencia entre una página en blanco en un libro y u
Typo:

```suggestion
Los componentes que se cierran automáticamente no solo comunican que no tienen contenido, sino que garantizan que no deben tener contenido. Es la diferencia entre una página en blanco en un libro y una con el texto "Está página fue intencionalmente dejada en blanco". También, su código es mas limpio sin la _tag_ de cerrado innecesaria.
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +<!-- En DOM templates -->
```suggestion
<!-- En plantillas del DOM -->
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +<!-- En componentes single-file, templates basados en string, y JSX -->
```suggestion
<!-- En componentes de un solo archivo, plantillas basadas en cadenas de texto, y JSX -->
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +<!-- En componentes single-file, templates basados en string, y JSX -->
Same here.

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +<!-- En DOM templates -->
The same suggestion than above here :)

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +- `<MyComponent>` es más disntivo visualmente que un elemento HTML simple que `<my-component>`, porque hay dos caracteres distintos (las dos mayúsculas), en lugar de solo uno (el guión).
```suggestion
- `<MyComponent>` es más distintivo visualmente que un elemento HTML simple que `<my-component>`, porque hay dos caracteres distintos (las dos mayúsculas), en lugar de solo uno (el guión).
```

2019-08-05 22:02 UTC, FLarra commented on src/v2/style-guide/index.md
> +- Si usted utiliza cualquier elemento no Vue en sus _templates_, como un componente web, PascalCase asegura que sus componente Vue se mantendrán distinguibles visualmente.
```suggestion
- Si usted utiliza cualquier elemento no Vue en sus plantillas, como un componente web, PascalCase asegura que sus componente Vue se mantendrán distinguibles visualmente.
```

2019-08-08 14:08 UTC, Tintef commented on src/v2/style-guide/index.md
> +Los componentes que se cierran automáticamente no solo comunican que no tienen contenido, sino que garantizan que no deben tener contendio. Es la diferencia entre una página en blanco en un libro y u
@FLarra That `más` must have an accent

2019-08-09 14:51 UTC, sxcamacho approved these changes

2019-08-09 14:52 UTC, merged