Tranlate - guide - migration - events
1950Labs/vuejs.org pull request #75
Opened 2019-10-01 22:39 UTC by Tintef

2019-10-01 23:30 UTC, sxcamacho requested changes

2019-10-01 23:30 UTC, sxcamacho commented on src/v2/guide/migration.md
> +La opción `events` ha sido removida. Ahora, Los manejadores de eventos deben ser registrados en el _hook_ `created`. Vea la [guía de migración de `$dispatch` y `$broadcoast`](#dispatch-and-broadcast-
```suggestion
La opción `events` ha sido removida. Ahora, Los manejadores de eventos deben ser registrados en el _hook_ `created`. Vea la [guía de migración de `$dispatch` y `$broadcast`](#dispatch-and-broadcast-replaced) para un ejemplo detallado.
```

2019-10-01 23:30 UTC, sxcamacho commented on src/v2/guide/migration.md
> +`$dispatch` and `$broadcast` han sido removidos en favor de una comunicación más explícita entre componentes y soluciones de manejo de estado más mantenibles, así como [Vuex](https://github.com/vuejs
```suggestion
`$dispatch` y `$broadcast` han sido removidos en favor de una comunicación más explícita entre componentes y soluciones de manejo de estado más mantenibles, así como [Vuex](https://github.com/vuejs/vuex).
```

2019-10-01 23:30 UTC, sxcamacho commented on src/v2/guide/migration.md
> +El problema es los flujos de eventos que dependen de la estructura del árbol de componentes pueden ser difíciles de razonar y muy fráfiles cuando el árobl se vuelve grande. No escala bien y no querem
```suggestion
El problema son los flujos de eventos que dependen de la estructura del árbol de componentes, pueden ser difíciles de razonar y muy frágiles cuando el árbol se vuelve grande. No escala bien y no queremos prepararnos para sufrir luego. `$dispatch` y `$broadcast` tampoco resuelven la comunicación entre componentes hermanos.
```

2019-10-01 23:30 UTC, sxcamacho commented on src/v2/guide/migration.md
> +Uno de los casos de uso más comúnes para estos métodos es para la comunicación directaentre un componente padre y sus hijos. En estos casos, usted pueden [escuchar a un `$emit` desde un componente hi
```suggestion
Uno de los casos de uso más común para estos métodos es para la comunicación directa entre un componente padre y sus hijos. En estos casos, usted pueden [escuchar a un `$emit` desde un componente hijo con `v-on`](components.html#Form-Input-Components-using-Custom-Events). Esto le permite mantener la conveniencia de los eventos.
```

2019-10-01 23:30 UTC, sxcamacho commented on src/v2/guide/migration.md
> +Sin embargo, cuando se quiere comunicar descendientes/antepasados distantes, `$emit` no le será de ayuda. En cambio, la forma más simple de resolver este problema sería utilizando un _event hub_ cent
```suggestion
Sin embargo, cuando se quiere comunicar descendientes/antepasados distantes, `$emit` no le será de ayuda. En cambio, la forma más simple de resolver este problema sería utilizando un _event hub_ centralizado. Esto tiene la ventaja de que permite comunicar componente sin importar dónde estén en el árbol de componentes - ¡incluso si son hermanos! Dado que las instancias de Vue implementan una interfaz de emisión de eventos, usted puede utilizar una instancia de Vue vacía para este propósito.
```

2019-10-01 23:30 UTC, sxcamacho commented on src/v2/guide/migration.md
> +// componente para comunicarlas entre sí.
```suggestion
// componente para comunicarlos entre sí.
```

2019-10-01 23:30 UTC, sxcamacho commented on src/v2/guide/migration.md
> +// de que una componente sea destruida.
```suggestion
// de que un componente sea destruido.
```

2019-10-01 23:30 UTC, sxcamacho commented on src/v2/guide/migration.md
> +Este patrón puede servir como reemplazo para `$dispatch` y `$broadcast` en escensario simples, pero para casos más complejos, se recomienda el uso de una capa dedicada al manejo de estado, tal como [
```suggestion
Este patrón puede servir como reemplazo para `$dispatch` y `$broadcast` en escenarios simples, pero para casos más complejos, se recomienda el uso de una capa dedicada al manejo de estado, tal como [Vuex](https://github.com/vuejs/vuex).
```

2019-10-01 23:42 UTC, Tintef commented
@sxcamacho Thanks for the review! All of them updated 😄

2019-10-02 00:25 UTC, sxcamacho approved these changes

2019-10-02 00:26 UTC, merged